import ffmpegPath from "ffmpeg-static";
import {createHash} from "node:crypto";
import {spawn} from "node:child_process";
import {readFile,stat} from "node:fs/promises";
import {resolve} from "node:path";
import {inspectMediaFile} from "../../shared/media-inspection";
import {DialogueScriptSchema,type DialogueScript} from "./book-dialogue-schema";
import {ComicDialogueStoryboardSchema,dialogueBubbleFor,type ComicDialogueStoryboard} from "./book-dialogue-storyboard";
import {buildDialogueVoiceFingerprint} from "./book-dialogue-voice";
import {BOOK_VIDEO_BLACKDETECT_FILTER} from "./book-video-verification";

const sha=(value:string|Buffer)=>createHash("sha256").update(value).digest("hex");
const refKey=(ref:{chapterId:string;page:number;blockId:string})=>`${ref.chapterId}:${ref.page}:${ref.blockId}`;
const sorted=(values:string[])=>[...new Set(values)].sort();
const normalized=(value:string)=>Array.from(value).filter((character)=>/[\p{L}\p{N}]/u.test(character)).join("");

export const assertDialogueSourceLock=(input:{lock:{inputHashes:Record<string,string>};script:string;expandedScript:string;selectedAngle:string;bookSynthesis:string}):void=>{for(const [key,value] of Object.entries({script:input.script,expandedScript:input.expandedScript,selectedAngle:input.selectedAngle,bookSynthesis:input.bookSynthesis})){if(input.lock.inputHashes[key]!==sha(value))throw new Error(`dialogue source lock 不一致：${key}`);}};

export const assertDialogueOutputContract=(input:{script:DialogueScript;scriptText:string;storyboard:ComicDialogueStoryboard;voiceManifest:{durationMs:number;fingerprint:string;audioSha256:string;voices:{xiaoyuan:{voice:string};douzai:{voice:string};narrator:{voice:string}};segments:Array<{turnId:string;speaker:string;text:string}>}}):void=>{
  const script=DialogueScriptSchema.parse(input.script);const storyboard=ComicDialogueStoryboardSchema.parse(input.storyboard);
  if(sha(input.scriptText)!==storyboard.dialogueScriptSha256)throw new Error("dialogue script lock 不一致");
  if(input.voiceManifest.durationMs!==script.durationMs||storyboard.format.durationMs!==script.durationMs)throw new Error("dialogue duration binding 不一致");
  if(input.voiceManifest.voices.xiaoyuan.voice===input.voiceManifest.voices.douzai.voice||storyboard.audio.voices.xiaoyuan!==input.voiceManifest.voices.xiaoyuan.voice||storyboard.audio.voices.douzai!==input.voiceManifest.voices.douzai.voice)throw new Error("双角色声音必须固定且明显不同");
  if(input.voiceManifest.fingerprint!==buildDialogueVoiceFingerprint(script)||storyboard.voiceFingerprint!==input.voiceManifest.fingerprint)throw new Error("dialogue voice fingerprint 不一致");if(storyboard.audio.sha256!==input.voiceManifest.audioSha256)throw new Error("dialogue voice audio binding 不一致");
  if(input.voiceManifest.segments.length!==script.turns.length||script.turns.some((turn,index)=>{const segment=input.voiceManifest.segments[index];return !segment||segment.turnId!==turn.id||segment.speaker!==turn.speaker||segment.text!==turn.voiceText;}))throw new Error("dialogue voice segment binding 不一致");
  if(JSON.stringify(storyboard.captions)!==JSON.stringify(script.captions))throw new Error("dialogue subtitles 与 script 不一致");
  for(const turn of script.turns){const captions=script.captions.filter((caption)=>caption.turnId===turn.id).sort((a,b)=>a.startMs-b.startMs);if(!captions.length||captions[0]!.startMs!==turn.speechStartMs||captions.at(-1)!.endMs!==turn.speechEndMs||captions.some((caption,index)=>{const previous=captions[index-1];const gap=previous?caption.startMs-previous.endMs:0;return caption.speaker!==turn.speaker||caption.startMs<turn.speechStartMs||caption.endMs>turn.speechEndMs||gap<0||gap>120;})||normalized(captions.map((caption)=>caption.text).join(""))!==normalized(turn.voiceText))throw new Error(`dialogue subtitle turn binding 不一致：${turn.id}`);}
  if(storyboard.shots.length!==script.turns.length)throw new Error("dialogue shot/turn binding 数量不一致");for(const [index,turn] of script.turns.entries()){const shot=storyboard.shots[index]!;if(shot.turnId!==turn.id||shot.startMs!==turn.startMs||shot.endMs!==turn.endMs||shot.speaker!==turn.speaker||shot.emotion!==turn.emotion||shot.characterPose!==turn.characterPose||shot.visualIntent!==turn.visualIntent||shot.shortBubble!==dialogueBubbleFor(turn.text))throw new Error(`dialogue shot/turn binding 不一致：${turn.id}`);const claims=sorted(shot.claimIds);const refs=sorted(shot.sourceRefs.map(refKey));if(JSON.stringify(claims)!==JSON.stringify(sorted(turn.claimIds))||JSON.stringify(refs)!==JSON.stringify(sorted(turn.sourceRefs.map(refKey))))throw new Error(`traceability 不一致：${turn.id}`);if(index>0&&shot.startMs!==storyboard.shots[index-1]!.endMs)throw new Error("dialogue shot timing 不连续");}
  if(storyboard.shots.some((shot)=>{const duration=shot.endMs-shot.startMs;const beats=[...new Set(shot.visualBeats.map((beat)=>beat.atMs))].sort((a,b)=>a-b);if(beats[0]!==0||beats.some((beat)=>beat<0||beat>=duration))return true;const points=[...beats,duration];return points.slice(1).some((point,index)=>point-points[index]!>6000);}))throw new Error("存在超过6秒无有效视觉变化的镜头");
  if(storyboard.characterScenePercentage<70||storyboard.infoCardPercentage>30)throw new Error("人物/信息卡比例不合格");
  if(script.quality.blockingIssues.length||script.quality.xiaoyuanTurns<20||script.quality.douzaiTurns<15||script.quality.narratorDurationShare>.1||script.quality.maxXiaoyuanMonologueMs>15000||!script.quality.phase3CCritiquePresent)throw new Error("dialogue content quality gate 未通过");
};

const assertNoBlank=(path:string)=>new Promise<void>((ok,reject)=>{if(!ffmpegPath)return reject(new Error("ffmpeg-static missing"));const child=spawn(ffmpegPath,["-hide_banner","-i",path,"-vf",BOOK_VIDEO_BLACKDETECT_FILTER,"-an","-f","null","-"],{stdio:["ignore","ignore","pipe"]});let stderr="";child.stderr.on("data",(chunk)=>{stderr+=String(chunk);});child.once("error",reject);child.once("exit",(code)=>code===0&&!/black_duration:(?:1(?:\.\d+)?|[2-9]\d*)/u.test(stderr)?ok():reject(new Error("final-dialogue-comic.mp4 存在空白场景")));});

export const verifyDialogueComicOutput=async(jobId:string)=>{
  const directory=resolve("output",jobId);const [scriptText,storyboardText,voiceManifestText,subtitlesText,sourceLockText,lockedScript,expandedScript,selectedAngle,bookSynthesis,voiceBytes,referenceBytes,voice,video,videoStats]=await Promise.all([
    readFile(resolve(directory,"dialogue-script.json"),"utf8"),readFile(resolve(directory,"comic-dialogue-storyboard.json"),"utf8"),readFile(resolve(directory,"dialogue-voice.json"),"utf8"),readFile(resolve(directory,"dialogue-subtitles.json"),"utf8"),readFile(resolve(directory,"dialogue-source-lock.json"),"utf8"),readFile(resolve(directory,"script.json"),"utf8"),readFile(resolve(directory,"video-script.json"),"utf8"),readFile(resolve(directory,"book/selected-angle.json"),"utf8"),readFile(resolve(directory,"book/book-synthesis.json"),"utf8"),readFile(resolve(directory,"dialogue-voice.mp3")),readFile(resolve(directory,"dialogue-assets/character-reference.png")),inspectMediaFile(resolve(directory,"dialogue-voice.mp3")),inspectMediaFile(resolve(directory,"final-dialogue-comic.mp4")),stat(resolve(directory,"final-dialogue-comic.mp4")),
  ]);const script=DialogueScriptSchema.parse(JSON.parse(scriptText));const storyboard=ComicDialogueStoryboardSchema.parse(JSON.parse(storyboardText));const manifest=JSON.parse(voiceManifestText);const subtitles=JSON.parse(subtitlesText);const sourceLock=JSON.parse(sourceLockText);assertDialogueSourceLock({lock:sourceLock,script:lockedScript,expandedScript,selectedAngle,bookSynthesis});if(storyboard.sourceLockSha256!==sha(sourceLockText))throw new Error("dialogue source lock artifact 不一致");assertDialogueOutputContract({script,scriptText,storyboard,voiceManifest:manifest});if(JSON.stringify(subtitles.captions)!==JSON.stringify(script.captions))throw new Error("dialogue subtitle artifact 不一致");if(sha(voiceBytes)!==storyboard.audio.sha256||sha(voiceBytes)!==manifest.audioSha256||sha(referenceBytes)!==storyboard.referenceImageSha256)throw new Error("dialogue voice 或角色图 hash 不一致");const videoTrack=video.videoTracks[0],audioTrack=video.audioTracks[0];if(!videoTrack||!audioTrack)throw new Error("final dialogue video 缺少音轨");if(video.durationMs<270000||video.durationMs>330000||Math.abs(video.durationMs-voice.durationMs)>2000)throw new Error("final dialogue video 时长不合格");if(videoTrack.codec!=="avc"||videoTrack.width!==1080||videoTrack.height!==1920||Math.abs(videoTrack.fps-30)>.05||audioTrack.codec!=="aac")throw new Error("final dialogue video 编码规格不合格");if(Math.abs(audioTrack.durationMs-voice.durationMs)>120)throw new Error("AAC 与 dialogue voice 不同步");if(videoStats.size<100000)throw new Error("final dialogue video 文件异常小");await assertNoBlank(resolve(directory,"final-dialogue-comic.mp4"));return{script,storyboard,voice,video};
};
